all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-35-90-82-55.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-44-245-176-69.us-west-2.compute.amazonaws.com